FROM python
RUN apt-get -y update \
   &&  apt-get -y install gdal-bin python-gdal python3-gdal libgdal-dev

RUN apt-get -y install llvm

RUN pip install rasterio \
    && pip install bokeh  
    # && pip install datashader


WORKDIR /home
