version: '3'

networks:
  tonynet:
    driver: overlay

services:
  product-service:
    image: tbutzer/product_server
    #build: ./product
    #volumes:
      #- ./product:/usr/src/app
    #ports:
      #- 8443:80
    networks:
      - tonynet

  pie-service:
    image: tbutzer/pie
    ports:
      - 8443:5006
    networks:
      - tonynet


  website:
    image: tbutzer/nginx_debug
    volumes:
      - ./nginx_conf/03-default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf:/etc/nginx/html
      # - ./nginx_conf/kan-proxy.conf:/etc/nginx/sites-available/kan-proxy.conf
    ports:
      - 8100:8100
      #- 8443:8443
      - 8080:80
    networks:
      - tonynet
    depends_on:
      - "pie-service"
    deploy:
      placement:
        constraints: [node.role == manager]

  debugger:
    image: tbutzer/bash-tester
    networks:
      - tonynet
