version: '3'

networks:
  tonynet:
    driver: overlay

services:

  view-service:
    image: tbutzer/view
    networks:
      - tonynet

  pie-service:
    image: tbutzer/pie
    networks:
      - tonynet
    depends_on:
      - "view-service"



  website:
    image: tbutzer/nginx_debug
    volumes:
      - ./nginx_conf/01-default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf:/etc/nginx/html
      # - ./nginx_conf/kan-proxy.conf:/etc/nginx/sites-available/kan-proxy.conf
    ports:
      #- 8100:8100
      #- 8443:8443
      - 8080:80
    networks:
      - tonynet
    depends_on:
      - "pie-service"
    deploy:
      placement:
        constraints: [node.role == manager]

