FROM jupyter/scipy-notebook


RUN conda install -c conda-forge ipywidgets ipyvolume bqplot scipy voila \
	&& npm install jupyterlab-datawidgets jupyter-threejs ipyvolume 


# RUN voila --enable_nbextensions=True
